services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-whisper_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - UPLOAD_DIR=/app/uploads
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
